title: "InspireLabs"
description: "Empowering elementary students through hands-on STEM education"
baseurl: ""
url: "https://inspirelabs.org"
theme: jekyll-theme-minimal

# Add this new section for navigation:
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation (now properly formatted)
nav:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about"
  - name: "Programs"
    url: "/programs"
  - name: "Contact"
    url: "/contact"
